# SPDX-FileCopyrightText: Copyright (c) 2020-2025, NVIDIA CORPORATION. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from typing import Generic, Tuple, TypeVar

T = TypeVar("T")

class Array(Generic[T]):
    def __init__(self, obj: T): ...
    @property
    def c_contiguous(self) -> bool: ...
    @property
    def f_contiguous(self) -> bool: ...
    @property
    def contiguous(self) -> bool: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> Tuple[int]: ...
    @property
    def strides(self) -> Tuple[int]: ...
    @property
    def cuda(self) -> bool: ...
    @property
    def obj(self) -> T: ...

def asarray(obj) -> Array: ...
