# Copyright (c) 2020-2021, NVIDIA CORPORATION. All rights reserved.
# See file LICENSE for terms.

from typing import Tuple

class Array:
    def __init__(self, obj: object): ...
    @property
    def c_contiguous(self) -> bool: ...
    @property
    def f_contiguous(self) -> bool: ...
    @property
    def contiguous(self) -> bool: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def shape(self) -> Tuple[int]: ...
    @property
    def strides(self) -> Tuple[int]: ...
