# Copyright (c) 2021-2022, NVIDIA CORPORATION. All rights reserved.
# See file LICENSE for terms.

from typing import Tuple

class CuFile:
    def __init__(self, file_path, flags="r") -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self) -> bool: ...
    def fileno(self) -> int: ...
    def open_flags(self) -> int: ...
    def read(self, buf, size: int = None, file_offset: int = 0) -> int: ...
    def write(self, buf, size: int = None, file_offset: int = 0) -> int: ...
