# Copyright (c) 2023, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') %}
{% set cuda_version='.'.join(environ.get('CUDA', '11.5').split('.')[:2]) %}
{% set cuda_major=cuda_version.split('.')[0] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: libkvikio
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_{{ date_string }}_h{{ PKG_HASH }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PARALLEL_LEVEL
    - VERSION_SUFFIX
    - PROJECT_FLASH
    - CMAKE_GENERATOR
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER
    - SCCACHE_S3_KEY_PREFIX=libkvikio-aarch64 # [aarch64]
    - SCCACHE_S3_KEY_PREFIX=libkvikio-linux64 # [linux64]
    - SCCACHE_BUCKET=rapids-sccache
    - SCCACHE_REGION=us-west-2
    - SCCACHE_IDLE_TIMEOUT=32768
    - CMAKE_EXTRA_ARGS
  run_exports:
    - {{ pin_subpackage("libkvikio", max_pin="x.x") }}
  ignore_run_exports_from:
    - {{ compiler('cuda') }}


requirements:
  build:
    - cmake >=3.20.1,!=3.25.0
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }} {{ cuda_version }}
    - sysroot_{{ target_platform }} {{ sysroot_version }}
  host:
    - cudatoolkit {{ cuda_version }}.*
  run:
    - {{ pin_compatible('cudatoolkit', max_pin='x', min_pin='x') }}

test:
  commands:
    - test -f $PREFIX/include/kvikio/file_handle.hpp

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: libkvikio library
