c_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

cxx_compiler_version:
  - 13  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - 11  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

cmake_version:
  - ">=3.26.4,!=3.30.0"

cuda_compiler:
  - cuda-nvcc  # [not os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]
  - nvcc  # [os.environ.get("RAPIDS_CUDA_VERSION", "").startswith("11")]

c_stdlib:
  - sysroot

c_stdlib_version:
  - "2.28"

# The CTK libraries below are missing from the conda-forge::cudatoolkit package
# for CUDA 11. The "*_host_*" version specifiers correspond to `11.8` packages
# and the "*_run_*" version specifiers correspond to `11.x` packages.

cuda11_libcufile_host_version:
  - "1.4.0.31"

cuda11_libcufile_run_version:
  - ">=1.0.0.82,<=1.4.0.31"

libcurl_version:
  - "==8.5.0"

nvcomp_version:
  - "=4.2.0.11"
