# SPDX-FileCopyrightText: Copyright (c) 2025, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'
  linux64: ${{ linux and x86_64 }}

package:
  name: kvikio
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  prefix_detection:
    # See https://github.com/rapidsai/build-planning/issues/160
    # Blanket ignore here as there are quite a few shared objects shipped in cugraph
    ignore_binary_files: True
  script:
    content: |
      # Remove `-fdebug-prefix-map` line from CFLAGS and CXXFLAGS so the
      # incrementing version number in the compile line doesn't break the
      # cache
      set -x
      export CFLAGS=$(echo $CFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
      export CXXFLAGS=$(echo $CXXFLAGS | sed -E 's@\-fdebug\-prefix\-map[^ ]*@@g')
      set +x

      ./build.sh -v kvikio
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
    env:
      CMAKE_C_COMPILER_LAUNCHER: ${{ env.get("CMAKE_C_COMPILER_LAUNCHER") }}
      CMAKE_CUDA_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CUDA_COMPILER_LAUNCHER") }}
      CMAKE_CXX_COMPILER_LAUNCHER: ${{ env.get("CMAKE_CXX_COMPILER_LAUNCHER") }}
      CMAKE_GENERATOR: ${{ env.get("CMAKE_GENERATOR") }}
      SCCACHE_BUCKET: ${{ env.get("SCCACHE_BUCKET") }}
      SCCACHE_IDLE_TIMEOUT: ${{ env.get("SCCACHE_IDLE_TIMEOUT") }}
      SCCACHE_REGION: ${{ env.get("SCCACHE_REGION") }}
      SCCACHE_S3_USE_SSL: ${{ env.get("SCCACHE_S3_USE_SSL") }}
      SCCACHE_S3_NO_CREDENTIALS: ${{ env.get("SCCACHE_S3_NO_CREDENTIALS") }}
      SCCACHE_S3_KEY_PREFIX: kvikio/${{ env.get("RAPIDS_CONDA_ARCH") }}/cuda${{ cuda_major }}

requirements:
  build:
    - cmake ${{ cmake_version }}
    - ninja
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("cuda") }}
    - cuda-version =${{ cuda_version }}
    - ${{ stdlib("c") }}
  host:
    - cuda-version =${{ cuda_version }}
    - cython >=3.0.0
    - libcurl ${{ libcurl_version }}
    - libkvikio =${{ version }}
    - pip
    - python =${{ py_version }}
    - rapids-build-backend >=0.4.0,<0.5.0.dev0
    - scikit-build-core >=0.10.0
    - cuda-cudart-dev
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - cupy >=13.6.0
    - libkvikio =${{ version }}
    - numpy >=1.23,<3.0a0
    - packaging
    - python
    - cuda-cudart
  ignore_run_exports:
    by_name:
      - cuda-cudart
      - cuda-version
      - libcurl
      - libkvikio

tests:
  - python:
      imports:
        - kvikio
      pip_check: false

about:
  homepage: ${{ load_from_file("python/kvikio/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/kvikio/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/kvikio/pyproject.toml").project.description }}
